services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres: /data/postgres
    ports:
      - "5432:1234"
    networks:
      - app-network
    restart: unless-stopped

  myApp:
    container_name: bank-app
    image: bank-app
    ports:
      - "8080:8087"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres: