spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_db_qa?createDatabaseIfNotExist=true&userSSL=false&userUnicode=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 9191
